### ISSUE TITLE
Skipped files list improvements

### ISSUE THREAD

**Issue by Valve** [piranha/goreplace#31]
I would like you to consider adding two things:
1. Human-friendly display of skipped files size

<img width="488" alt="machine_ _valentin_macbook-pro____projects_evrone_machine_ _zsh_ _153x42_and_category_ids_rb_-__users_valentin_projects_evrone_machine_-_atom" src="https://cloud.githubusercontent.com/assets/27387/8906018/a30baf5e-3473-11e5-88a2-4735a352c1cb.png">

i.e. show 1.2M instead of 1223479

2. Have the size of skipped files be configurable (either a configuration file or a command line option)

Thanks!

**Comment by piranha** [comment]
Fixed in #32

**Comment by piranha** [comment]
I mean first part fixed there. :) Having configurable size also sounds fine.

**Comment by Valve** [comment]
Thanks, thanks :heart:

**Comment by Valve** [comment]
Thank you, your tool is indispensable! Using it daily and loving it.

**Comment by piranha** [comment]
Thank you, it's a delight to hear that. :)
